### ISSUE TITLE
Error: Cannot find module in 0.8.1

### ISSUE THREAD

**Issue by khromov** [vercel/mcp-adapter#47]
Since updating to 0.8.2 / 0.8.1 I get the following error. 0.8.0 or lower works.

```
Error: Cannot find module '/Users/k/Documents/GitHub/llmctx/node_modules/@modelcontextprotocol/sdk/dist/cjs/server/auth/errors'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1441:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1430:15)
    at resolveExports (node:internal/modules/cjs/loader:661:14)
    at Module._findPath (node:internal/modules/cjs/loader:753:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1391:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Module._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/k/Documents/GitHub/llmctx/node_modules/@modelcontextprotocol/sdk'
}

Node.js v24.1.0
```

From this +server.ts in a SvelteKit Project:

```ts
import { z } from 'zod'
import type { RequestHandler } from './$types'
import { createMcpHandler } from '@vercel/mcp-adapter'
import { env } from '$env/dynamic/private'

const handler = createMcpHandler(
	(server) => {
		server.tool(
			'roll_dice',
			'Rolls an N-sided die',
			{ sides: z.number().int().min(2) },
			async ({ sides }) => {
				console.log({ sides })
				const value = 1 + Math.floor(Math.random() * sides)
				return {
					content: [{ type: 'text', text: `🎲 You rolled a ${value}!` }]
				}
			}
		)
	},
	{},
	{
		maxDuration: 3600,
		basePath: '/mcp',
		verboseLogs: true,
		redisUrl: env.REDIS_URL ? env.REDIS_URL : 'redis://127.0.0.1:6379'
	}
)

export const GET: RequestHandler = async ({ request }) => {
	return handler(request)
}

export const POST: RequestHandler = async ({ request }) => {
	return handler(request)
}

export const DELETE: RequestHandler = async ({ request }) => {
	return handler(request)
}

```

**Comment by dvoytenko** [comment]
@khromov Could we ask:

1. Do you use `npm`, `pnpm`, or something else?
2. What version
3. Are you by any chance use `--legacy-peer-deps`?

**Comment by quuu** [comment]
@khromov checking in on this!

**Comment by khromov** [comment]
I'm just using the default SvelteKit setup, nothing special. It's enough to just import the package and then build. Here's a very basic repro (run `npm run build`):
https://www.sveltelab.dev/pp5m73dr8800p96

**Comment by CarlosZiegler** [comment]
<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/aad1b4c1-906f-419a-95f8-be0ac61f0002" />

**Comment by quuu** [comment]
@khromov @CarlosZiegler just debugged this with @elliott-with-the-longest-name-on-github 

if you upgrade the `@vercel/mcp-adapter@0.10.0`, the package is fixed, and i shrunk the dependencies as well!

please let me know if you're still running into this error
